#!/usr/bin/env python3

# Typically ignore this.
# pylint: disable=invalid-name

# Disable these because this is our standard setup
# pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position

import os, shutil, sys

CIMEROOT = os.environ.get("CIMEROOT")
if CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
sys.path.append(os.path.join(CIMEROOT, "scripts", "Tools"))


# pylint: disable=unused-argument
###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    """Build the SCHISM input """

    # Build the component namelist
    if compname != "schism":
        raise AttributeError

    return

###############################################################################
def _main_func():

    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildnml(case, caseroot, "schism")

if __name__ == "__main__":
    _main_func()
